-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bid
(
    bid_id integer NOT NULL,
    car_product_id integer,
    buyer_id integer,
    date_bid date,
    bid_price integer,
    bid_status character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT bid_pkey PRIMARY KEY (bid_id)
);

CREATE TABLE IF NOT EXISTS public.buyer
(
    buyer_id integer NOT NULL,
    nama_buyer character varying(100) COLLATE pg_catalog."default" NOT NULL,
    kontak integer,
    city_id integer,
    CONSTRAINT buyer_pkey PRIMARY KEY (buyer_id)
);

CREATE TABLE IF NOT EXISTS public.car_product
(
    product_id integer NOT NULL,
    brand character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    body_type character varying(100) COLLATE pg_catalog."default",
    year integer,
    price integer,
    seller_id integer,
    CONSTRAINT car_product_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.city
(
    city_id integer NOT NULL,
    nama_kota character varying(100) COLLATE pg_catalog."default" NOT NULL,
    location point,
    CONSTRAINT city_pkey PRIMARY KEY (city_id)
);

CREATE TABLE IF NOT EXISTS public.iklan
(
    iklan_id integer NOT NULL,
    car_product_id integer,
    seller_id integer,
    date_post date,
    CONSTRAINT iklan_pkey PRIMARY KEY (iklan_id)
);

CREATE TABLE IF NOT EXISTS public.seller
(
    seller_id integer NOT NULL,
    nama_seller character varying(100) COLLATE pg_catalog."default" NOT NULL,
    kontak integer,
    city_id integer,
    CONSTRAINT seller_pkey PRIMARY KEY (seller_id)
);

ALTER TABLE IF EXISTS public.bid
    ADD CONSTRAINT bid_ibfk_1 FOREIGN KEY (car_product_id)
    REFERENCES public.car_product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bid
    ADD CONSTRAINT bid_ibfk_2 FOREIGN KEY (buyer_id)
    REFERENCES public.buyer (buyer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.buyer
    ADD CONSTRAINT buyer_ibfk_1 FOREIGN KEY (city_id)
    REFERENCES public.city (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.car_product
    ADD CONSTRAINT car_product_ibfk_1 FOREIGN KEY (seller_id)
    REFERENCES public.seller (seller_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.iklan
    ADD CONSTRAINT iklan_ibfk_1 FOREIGN KEY (car_product_id)
    REFERENCES public.car_product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.iklan
    ADD CONSTRAINT iklan_ibfk_2 FOREIGN KEY (seller_id)
    REFERENCES public.seller (seller_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.seller
    ADD CONSTRAINT seller_ibfk_1 FOREIGN KEY (city_id)
    REFERENCES public.city (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;